services:
  # 1. Service Aplikasi (PHP + Laravel)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cinema-app
    volumes:
      - .:/var/www  # Menghubungkan folder Windows ke Kontainer
    networks:
      - laravel-net

  # 2. Service Web Server (Nginx)
  web:
    image: nginx:alpine
    container_name: cinema-web
    restart: unless-stopped
    ports:
      - "8000:80"  # Kita akan akses via localhost:8000
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel-net

  # 3. Service Database (MySQL)
  db:
    image: mysql:8.0
    container_name: cinema-db
    restart: always
    environment:
      MYSQL_DATABASE: cinema_db
      MYSQL_ROOT_PASSWORD: aura1101
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel-net

volumes:
  dbdata:

networks:
  laravel-net:
    driver: bridge